Add design menu
docomoinnovations/cloud_dashboard pull request #31
Opened 2021-11-05 09:49 UTC by RyoYamashita765

2021-11-05 10:58 UTC, naoi requested changes
@RyoYamashita765 I posted my comments.  Thanks!

2021-11-05 10:58 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +          }
@RyoYamashita765 This can be:

```suggestion
          record2 = CONVERT_KEY_VALUE_CRLF_DICT[key].includes('Pods ')
            ? CONVERT_KEY_VALUE_CRLF_DICT[key] + value
            : CONVERT_KEY_VALUE_CRLF_DICT[key] + roundNumber(valueFloat, 2);
```

2021-11-05 10:58 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +        }
@RyoYamashita765 This can be:

```suggestion
        dataRecord.value[launchTemplateColumn.name] = temp.length >= 1
          ? temp[0].labelName
          : rawValue;
```

2021-11-09 02:02 UTC, RyoYamashita765 commented on cloud_dashboard/src/service/utility.ts
> +          }
@naoi I've pushed a commit to fix that. Please review it.

2021-11-09 02:03 UTC, RyoYamashita765 commented on cloud_dashboard/src/service/utility.ts
> +        }
@naoi I've pushed a commit to fix that. Also, the processing in the functions has been organized to improve readability.　Please review it.

2021-11-09 02:38 UTC, naoi requested changes
@RyoYamashita765 Thank you for the update.  I posted my comments.  Thanks!

2021-11-09 02:38 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +  const temp = data.split('\n');
@RyoYamashita765 This can be:

```suggestion
  const records = data.split('\n');
```

2021-11-09 02:38 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +  for (const record of temp) {
@RyoYamashita765 This can be:

```suggestion
  for (const record of records) {
```

2021-11-09 02:38 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +  const temp2: string[] = [];
@RyoYamashita765 This can be (more meaningful variable name):

```suggestion
  const results: string[] = [];
```

2021-11-09 02:38 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +    temp2.push(record2);
@RyoYamashita765 This can be:

```suggestion
    results.push(record2);
```

2021-11-09 02:38 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +  return temp2.sort((a, b) => {
@RyoYamashita765 This can be:

```suggestion
  return results.sort((a, b) => {
```

2021-11-09 02:42 UTC, naoi requested changes
@RyoYamashita765 I added my comments.  Thanks!

2021-11-09 02:42 UTC, naoi commented on cloud_dashboard/src/molecules/DataTableRow.tsx
> +    const temp = text.split('\n');
This can be:

```suggestion
    const data = text.split('\n');
```

Or more meaningful variable name.

2021-11-09 02:42 UTC, naoi commented on cloud_dashboard/src/molecules/DataTableRow.tsx
> +      {temp.map((r, index) => {
@RyoYamashita765 This can be:

```suggestion
      {data.map((r, index) => {
```

2021-11-09 02:42 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +      const temp = cloudContextList.filter((r) => {
@RyoYamashita765 This can be:

```suggestion
      const cloudContexts = cloudContextList.filter((r) => {
```

2021-11-09 02:42 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +        ? temp[0].labelName
@RyoYamashita765 This can be:

```suggestion
      dataRecord.value[launchTemplateColumn.name] = cloudContexts.length >= 1
        ? cloudContexts[0].labelName
```

2021-11-09 05:31 UTC, RyoYamashita765 commented on cloud_dashboard/src/service/utility.ts
> +        ? temp[0].labelName
@naoi This and other variable names that were labeled as "temp" in the source code have been corrected. Please check it.

2021-11-09 08:43 UTC, naoi commented on cloud_dashboard/src/service/utility.ts
> +    temp2.push(record2);
@RyoYamashita765 Could you please consider to rename from `record2` to some other variable name w/o the number `2`?  Thanks!

2021-11-10 01:25 UTC, merged