Add Spinner component for CallbackPage
docomoinnovations/cloud_dashboard pull request #33
Opened 2021-11-11 03:22 UTC by RyoYamashita765

<img width="270" alt="スクリーンショット 2021-11-11 12 07 04" src="https://user-images.githubusercontent.com/48265860/141231468-bae6dc94-db41-4ba5-9812-2edea9e90b84.png">

2021-11-11 07:08 UTC, naoi requested changes

2021-11-11 07:08 UTC, naoi commented on cloud_dashboard/src/organisms/CallbackForm.tsx
> +      }}>Please waiting...</span>
@RyoYamashita765 It is natural to say:

```suggestion
      }}>One moment, please...</span>
```

2021-11-12 01:00 UTC, RyoYamashita765 commented on cloud_dashboard/src/organisms/CallbackForm.tsx
> +      }}>Please waiting...</span>
@naoi I fixed this message. Please check it.

2021-11-12 01:49 UTC, naoi commented
Thank you for the update.  Could you please fix the following error while applying the patch?

```
$ git apply -v /tmp/33.diff.1 
Checking patch LICENSE...
/tmp/33.diff.1:280: new blank line at EOF.
+
Checking patch cloud_dashboard/package.json...
Checking patch cloud_dashboard/src/App.tsx...
Checking patch cloud_dashboard/src/organisms/CallbackForm.tsx...
Checking patch cloud_dashboard/yarn.lock...
Checking patch css/2.chunk.css...
Checking patch js/2.chunk.js...
Checking patch js/3.chunk.js...
Checking patch js/main.chunk.js...
Checking patch js/runtime-main.js...
Applied patch LICENSE cleanly.
Applied patch cloud_dashboard/package.json cleanly.
Applied patch cloud_dashboard/src/App.tsx cleanly.
Applied patch cloud_dashboard/src/organisms/CallbackForm.tsx cleanly.
Applied patch cloud_dashboard/yarn.lock cleanly.
Applied patch css/2.chunk.css cleanly.
Applied patch js/2.chunk.js cleanly.
Applied patch js/3.chunk.js cleanly.
Applied patch js/main.chunk.js cleanly.
Applied patch js/runtime-main.js cleanly.
warning: 1 line adds whitespace errors.
```

Thanks!

2021-11-12 01:53 UTC, RyoYamashita765 commented
> warning: 1 line adds whitespace errors.
I do not know why you are getting this Warning.
But am I correct in understanding that the patch itself can be applied and does not interfere with the operation?

2021-11-12 02:27 UTC, naoi commented
@RyoYamashita765 The patch itself is correct.  On the other hand, can you remove the CRLF (a blank line) at the end of line of `LICENSE`?  I'm using `git` command on Ubuntu 20.04.3 LTS.

2021-11-12 03:22 UTC, RyoYamashita765 commented
@naoi I understand. I removed CRLF at the end of the LICENCE file.

2021-11-12 03:52 UTC, naoi commented on cloud_dashboard/src/organisms/CallbackForm.tsx
> +      }}>One moment, please...</span>
@RyoYamashita765 What about this?

```suggestion
        marginLeft: '2rem'
      }}>Orchestrating the clouds...</span>
```

2021-11-12 03:53 UTC, naoi requested changes
@RyoYamashita765 Thank you for the update.  Now the patch is ready but I would like you to review my suggestion.  Thanks!

2021-11-12 05:01 UTC, RyoYamashita765 commented
@naoi I changed the message when the login process is being performed. Please check it.

![スクリーンショット 2021-11-12 14 00 45](https://user-images.githubusercontent.com/48265860/141412497-b508ee4b-b8e2-495b-a130-8d9cfe2805e6.png)

2021-11-12 05:59 UTC, naoi requested changes
@RyoYamashita765 Thank you for the update.  I posted my comment.  Also, can you change the label of the login button from `login` to `Log into Cloud Dashboard`?  Thanks!

2021-11-12 05:59 UTC, naoi commented on cloud_dashboard/src/organisms/CallbackForm.tsx
> +      }}>Orchestrating the clouds...</span>
@RyoYamashita765 Thank you for the update.  On my second thought, can you change to:

```suggestion
      }}>Orchestrating clouds...</span>
```

2021-11-12 06:32 UTC, RyoYamashita765 commented on cloud_dashboard/src/organisms/CallbackForm.tsx
> +      }}>Orchestrating the clouds...</span>
@naoi I changed the button and the message. Is there any problem with this design?

![スクリーンショット 2021-11-12 15 31 07](https://user-images.githubusercontent.com/48265860/141421087-49277b8b-69f0-4302-9f7b-fb9c6954c91e.png)

![スクリーンショット 2021-11-12 15 31 15](https://user-images.githubusercontent.com/48265860/141421096-09307e05-5728-419c-ab59-14b96e658cd3.png)

2021-11-12 06:38 UTC, naoi commented
@RyoYamashita765  As I mentioned in my previous comment, can you change the label of the login button from `login` to `Log in`? Thanks!

2021-11-12 06:44 UTC, RyoYamashita765 commented
@naoi I changed the button text from "Log into Clouddashboard" to "Log in". Is this correct?
![スクリーンショット 2021-11-12 15 43 57](https://user-images.githubusercontent.com/48265860/141422374-6a2ec6bb-691a-4b65-8579-264010c20a6b.png)

2021-11-12 07:06 UTC, naoi commented
@RyoYamashita765 Yes, that is correct.  Can you push the code, please?

2021-11-12 07:19 UTC, naoi commented
@RyoYamashita765 Thank you for the update.  Perfect, I'll merge this PR.

2021-11-12 07:19 UTC, merged