Use d3-horizon-chart for metric graph in entity detail info panel
docomoinnovations/cloud_dashboard pull request #50
Opened 2021-11-24 02:33 UTC by RyoYamashita765

<img width="1272" alt="スクリーンショット 2021-11-24 11 32 07" src="https://user-images.githubusercontent.com/48265860/143160979-8f03f55b-caf3-45ab-9277-8f610a04d6ad.png">

2021-11-24 11:24 UTC, naoi requested changes
@RyoYamashita765 Thank you for the patch.  I posted my comments.  Thanks!

2021-11-24 11:24 UTC, naoi commented on cloud_dashboard/src/molecules/D3MetricsBlock.tsx
> +              } />
@RyoYamashita765 This can be reduce one indent?

```suggestion
            height={100} titleFontSize={10} titleColor="white" title={data.title}
            colors={
              index === 0
                ? ['#edf8e9', '#bae4b3', '#74c476', '#31a354', '#006d2c']
                : ['#e9f8f4', '#b3e4dc', '#74c1c4', '#317fa3', '#003f6d']
            } />
```

2021-11-24 11:24 UTC, naoi commented on cloud_dashboard/src/molecules/D3HorizonChartSampleBlock.tsx
> +          for (let i = 0; i < temp.options.length; i += 1) {
@RyoYamashita765 This can be:

```suggestion
          for (let i = 0; i < temp.options.length; i++) {
```

2021-11-24 11:56 UTC, naoi commented
@RyoYamashita765 Also, I found the following error while compiling the TypeScript:

```
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error d3@7.1.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.0"
error Found incompatible module
```

2021-11-25 01:04 UTC, RyoYamashita765 commented on cloud_dashboard/src/molecules/D3MetricsBlock.tsx
> +              } />
@naoi VSCode's Formatter process indents attribute descriptions by one level relative to the parentheses of the tag. I committed this because I thought it was fine, but do I really need to align the indentation to the same height as the tag?

```typescript
            // tag indent line
            <D3HorizonChart id={`metric-${index}`} dataSet={
              data.record.map((r) => {
                return [new Date(r.x * 1000), r.y];
              })
            }
              // attributes' indent line
              height={100} titleFontSize={10} titleColor="white" title={data.title}
              colors={
                index === 0
                  ? ['#edf8e9', '#bae4b3', '#74c476', '#31a354', '#006d2c']
                  : ['#e9f8f4', '#b3e4dc', '#74c1c4', '#317fa3', '#003f6d']
              } />
```

However, it doesn't look good if the indentation of the parentheses is different between the colors attribute and the dataSet attribute, so I will submit it with the same indentation.

```typescript
            <D3HorizonChart
              id={`metric-${index}`}
              dataSet={
                data.record.map((r) => {
                  return [new Date(r.x * 1000), r.y];
                })
              }
              height={100}
              titleFontSize={10}
              titleColor="white"
              title={data.title}
              colors={
                index === 0
                  ? ['#edf8e9', '#bae4b3', '#74c476', '#31a354', '#006d2c']
                  : ['#e9f8f4', '#b3e4dc', '#74c1c4', '#317fa3', '#003f6d']
              } />
```

2021-11-25 01:13 UTC, RyoYamashita765 commented
@naoi I am using node.js v16. The previous error message seems to indicate that we need to use node.js v12 or later when building.

2021-11-25 01:38 UTC, naoi commented on cloud_dashboard/src/molecules/D3MetricsBlock.tsx
> +              } />
@RyoYamashita765 OK, Thanks!

2021-11-25 03:50 UTC, merged